### ISSUE TITLE
Indenting with = does not work

### ISSUE THREAD

**Issue by partounian** [sgur/vim-editorconfig#12]
I have noticed on projects with an .editorconfig running `gg=G` does not do anything.

**Comment by andymass** [comment]
This is a wild guess, but maybe you have `&shiftwidth=0` and your filetype's `indentexpr` uses `&shiftwidth` instead of `shiftwidth()`.

**Comment by mcepl** [comment]
WORKSFORME ... @sgur, I guess when we have no response from @partounian in more than half year, this could be closed?

**Comment by partounian** [comment]
I do not believe this is an issue anymore.
