### ISSUE TITLE
Don't run when committing with git (editing .git/COMMIT_MSG)

### ISSUE THREAD

**Issue by chearon** [sgur/vim-editorconfig#14]
This would be nice to have, maybe check if the path has `.git` in it on `BufRead` or check for `ft=gitcommit` or something.

**Comment by davidosomething** [comment]
this should be able to handle that:
https://github.com/sgur/vim-editorconfig/commit/f3befbfa17733b48448ed91a2974f5782278c5fa#diff-04c6e90faac2675aa89e2176d2eec7d8R60

you may need to create a gitcommit filetype if you don't have one

**Comment by chearon** [comment]
Should have thought to look for an option. Thanks!
