### ISSUE TITLE
Why is the directory check needed?

### ISSUE THREAD

**Issue by davidosomething** [sgur/vim-editorconfig#17]
Why is the directory check needed here?
https://github.com/sgur/vim-editorconfig/blob/master/plugin/editorconfig.vim#L25

**Comment by sgur** [comment]
Well... I encountered an error on the buffer created by one of my installed plugins.
But I have no idea about which plugin occur the error. I can't reproduce.
Maybe the directory check is unnecessary, I think.

**Comment by davidosomething** [comment]
it may have been pre-blacklist support, since fugitive buffers and similar non-files wouldn't have a cwd to find an .editorconfig in.

I'm running without the check in my vimrc, works fine
