### ISSUE TITLE
max_line_length should support value off

### ISSUE THREAD

**Issue by mcepl** [sgur/vim-editorconfig#26]
https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties mentions ``'off'`` as a possible value of ``max_line_length`` property. We probably should do nothing on it (“use the editor settings” probably means just that), but we shouldn't choke on it (as we do in https://github.com/sgur/vim-editorconfig/blob/master/autoload/editorconfig/max_line_length.vim#L13 ).

**Comment by sgur** [comment]
I had forgotten the 'off' value.
Thank you for your contribution!
