### ISSUE TITLE
The claim on README.md is no longer true (editorconfig-vim requires if_python interface or external python interpreter.)

### ISSUE THREAD

**Issue by krishnakumarg1984** [sgur/vim-editorconfig#45]
In your `README.md` you have the following claim

>editorconfig-vim is official vim plugin for EditorConfig. This requires if_python interface or external python interpreter.

As of May 21, 2019 this is no longer true.  See [here](https://github.com/editorconfig/editorconfig-vim/pull/119).

In the wake of this development, can you 
 * Please update the `README.md` suitably
 * Offer a fresh comparison between your plugin and the official one to help out new users

**Comment by keithbowes** [comment]
I'm going to try the official one.  I've made various improvements of this one (and there are also some bugs that I have no idea how to fix), but I can't remember all of them to send a pull request.  It's best not to require if_python, as AFAIK, Vim 9 will remove support for external interpreters (they're already only available if you explicitly enable them with ./configure).
