### ISSUE TITLE
unsupported value insert_final_newline=true 

### ISSUE THREAD

**Issue by breneser** [sgur/vim-editorconfig#8]
Using below configuration, I get unsupported value warning:

```
root = true

[*]
indent_style = space
indent_size = 2
charset = utf-8
trim_trailing_whitespace = true
end_of_line = lf
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false

[*.sh]
indent_size = 4
```

```
insert_final_newline#execute[2]..<SNR>98_bool:
line    6:
editroconfig: unsupported value: insert_final_newline=true 

```

Documentation says insert_final_newline is supported. Any ideas ?

Also, VIM version I use is 8.0.86

**Comment by sgur** [comment]
I think there are trailing spaces at the end of the `insert_final_newline = true` line. Is it right?
This plugin's parser doesn't permit trailing spaces in `.editorconfig`. I'll fix it to permit trailing spaces.

**Comment by sgur** [comment]
> This plugin's parser doesn't permit trailing spaces in `.editorconfig`. I'll fix it to permit trailing spaces.

I fixed it. please try with the latest version.

**Comment by mcepl** [comment]
I guess, @breneser ’s inaction can be considered as a verification of the fix?

**Comment by breneser** [comment]
@mcepl Sorry, i must have missed the conversation. 

After sgur's answer on trailing space not working i noticed the spaces at the end and deleting them worked. Never checked if it was fixed. Will have a look in a couple hours.

**Comment by breneser** [comment]
@mcepl Can confirm this is is fixed. No errors with trailing whitespaces. Thanks folks.

**Comment by mcepl** [comment]
@sgur I guess, you can close this one?
